"""teste backpopulates

Revision ID: 28e5ae66cc2b
Revises: 84b0efa3afc6
Create Date: 2022-09-21 11:10:47.206985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e5ae66cc2b'
down_revision = '84b0efa3afc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
