"""tabela produto/usuarios

Revision ID: 56964c6dbec6
Revises: 5a1c3b3bbf71
Create Date: 2022-09-13 15:19:43.354903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56964c6dbec6'
down_revision = '5a1c3b3bbf71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
